### PR TITLE
Parse custom formats when changing input text

### PR DESCRIPTION
**Pull request by t0m3k**
Parse custom formats when using input text

### CODE REVIEW

**Comment by AnalogMemory** [comment]
Would love to fix to be added soon 🙏 

@t0m3k you'll need to rebase the latest changes with this

cc @onesine

**Comment by onesine** [comment]
You are right @AnalogMemory

**Comment by t0m3k** [comment]
Fixed as of 21/04/2023 @AnalogMemory @onesine

**Comment by onesine** [comment]
Hi @t0m3k 👋 
Sorry for the delay.
Thanks for this PR.

**Comment by walidmahade** [comment]
I see this PR is merged but still don't get the user input to trigger onchange.
@t0m3k Do I need do anything special? like a specific format?

**Comment by onesine** [comment]
Hi @walidmahade  👋  

Thanks for your feedback.

The PR is indeed merger, but we haven't released a new version yet. We are waiting to have a number of features before we can release a new version.

**Comment by poshiemaaat** [comment]
@onesine could releasing be made a priority? It would be nice to have one new feature if it's ready rather than wait for a bundle 😄

**Comment by onesine** [comment]
Hi @poshiemaaat 👋 .

I understand your concern.

So I'll publish a new release.

**Comment by poshiemaaat** [comment]
Woo hoo! Thank you @onesine 

Now that I tried it out, it does look like hard coded input slices is not necessarily working. For example, if I use 
```tsx
<Datepicker
      asSingle={true}
      displayFormat="MMMM D, YYYY"
/>
```

This doesn't update, correct? The issue is that "May 11, 2023" is more than 10 characters, making it an invalid date. I could circumvent this by removing the year for now. I'm also not entirely sure what the best solution may be; perhaps slice on either nothing or the `~` character (or custom character)?

Want me to write a bug ticket or try to create a PR?

**Comment by t0m3k** [comment]
@poshiemaaat thanks for input. I've created a new pull request with the issue hopefully solved. https://github.com/onesine/react-tailwindcss-datepicker/pull/132

I tried specifically your date format both asSingle and not and seemed to be working, as well as for other popular date formats.

Thanks for input

**Pull request merged**
