### PR TITLE
Add Start Week Day options

### PR DESCRIPTION
**Pull request by handinugroho**
Optional props added:
- startWeekOn: default is on Sunday.

Possible values:
`["sun", "mon", "tue", "wed", "thu", "fri", "sat"]`

### CODE REVIEW

**Review by JefteCaro — COMMENTED** [review]
Hi @handinugroho 

Thank you for this PR.

**Comment by microspace** [comment]
I think start of the week day should depend on locale

**Comment by onesine** [comment]
Sorry, I hadn't paid attention to the PR since. Thanks @handinugroho for this PR.

I think it would be interesting to incorporate @microspace 's suggestion. That is, by default we use the regional settings to determine the first day of the week. But people will be free to change this value.

**Review by onesine — COMMENTED** [review]
Can you consider the proposal in the PR conversation

**Comment by handinugroho** [comment]
I will try to implement this

**Comment by handinugroho** [comment]
I just updated it, now the default start week day is using the i18n configuration specified

**Pull request merged**
