### PR TITLE
Enhancing React Library Feature: Introducing Time Picker Capability

### PR DESCRIPTION
**Pull request by julioflima**
Hey folks! (@onesine ) Big news! I've just dropped a slick new update this library, and we couldn't be more excited to share it with you. But first, let's give a round of applause to the about this library. Seriously, the structure they've cooked up is like a dream to work with, especially when you throw Next.js into the mix. Smooth sailing all the way!

Now, onto the juicy stuff. I've added a Time Picker feature, we didn't even have to add extra libraries, it could kept it clean and mean, sticking to what we've got and just sprinkling in some magic.

One of the standout additions in this update is the introduction of the `asTimePicker` parameter. By simply toggling this boolean flag, users can now effortlessly transform their components into time pickers, expanding the library's versatility without compromising its simplicity.

```typescript
asTimePicker?: boolean;
```

Below, you'll find the interface detailing the implementation of the Time Picker feature, along with a clear demonstration of the return format in ISO hour. This ensures consistency and compatibility across various environments, empowering developers to integrate this feature seamlessly into their projects.

Thank you for your continued support and enthusiasm for this library. Together, let's continue pushing to improve this! 🚀

image

image

image

### CODE REVIEW

**Comment by CaptainT33mo** [comment]
@julioflima , Great addition to this library but can you also provide more examples of this feature like can we select time separately or it will always be 12:00 AM?

**Comment by julioflima** [comment]
@CaptainT33mo Thank you! I updated for more examples.

I could modify to attend more features, I spent a lot of time, improving this, so things that could be added:

1. Timepicker with better dropdown, using Headlessui. https://headlessui.com/react/menu
2. Timepicker with range date.

**Comment by larserikgk** [comment]
Good work! I looked through the code and can't see any support for 24h time format. Am I missing something or is there only support for pm/am format?

**Comment by julioflima** [comment]
> Good work! I looked through the code and can't see any support for 24h time format. Am I missing something or is there only support for pm/am format?

After the PR been approved, we could add this not a problem at all. 


1. Timepicker with better dropdown, using Headlessui. https://headlessui.com/react/menu
2. Timepicker with range date.
3. Support for 24h.

**Comment by InaKim98** [comment]
First, thank you for updating this feature, date time
I wonder when I can use this feature with new version of library.
I mean when you publish new version (now, v1.6.6 doesn't have this feature)

**Comment by julioflima** [comment]
> First, thank you for updating this feature, date time
> 
> I wonder when I can use this feature with new version of library.
> 
> I mean when you publish new version (now, v1.6.6 doesn't have this feature)

It depends on @onesine approval.

**Comment by maukoese** [comment]
@onesine any chance this can be approved?

**Comment by mschipperheyn** [comment]
Is there any way to get this as a beta so we can start using it? Or would we have to inline the whole shabang?

**Comment by julioflima** [comment]
Seams like this will move forwards, @onesine have said this to me:

Please take merge the #266.

image

**Comment by julioflima** [comment]
It's launched!

**Pull request closed without merging**
